# Generated by Django 4.0.6 on 2023-03-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='SizeVariant',
            new_name='size_variant',
        ),
    ]
